<?xml version="1.0" encoding="utf-8"?><Database Name="MovieDB" Class="MovieDBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BRAHMAM\SQLEXPRESS;Initial Catalog=MovieDB;Integrated Security=True" SettingsObjectName="HealthCare.PromptRx.Infrastructure.Data.Properties.Settings" SettingsPropertyName="MovieDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Movie" Member="Movies">
    <Type Name="Movie">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Director" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Writers" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Stars" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>